#!/bin/sh
set -e
reposit_name=$1
test -z $reposit_name && echo "Repository name required." 1>&2 && exit 1
echo -n "Enter Your Github Username : "
read uname
echo "====== Using GITHUB API ======="
curl -u "$uname" https://api.github.com/user/repos -d "{\"name\":\"$reposit_name\"}"
